cache ip addresses during startup
bitnami/bitnami-docker-redis-cluster pull request #14
Opened 2020-10-24 18:28 UTC by larryzhu2018

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

2020-10-26 08:04 UTC, miguelaeh reviewed
Hi @larryzhu2018 ,
Thank you very much for the PR!
Could you please update the description and explain what is this PR doing and why it is necessay?

2020-10-27 16:24 UTC, larryzhu2018 commented
> Hi @larryzhu2018 ,
> Thank you very much for the PR!
> Could you please update the description and explain what is this PR doing and why it is necessay?

 - Describe the scope of your change - i.e. what the change does.
we have a redis-cluster of 62 nodes, and during the startup it takes a while to look up IP and builds the cluster map, and when the node is restarted, it will need to do the work again. This is to save the work by adding the checkpoints and if it evens fully pass the startup, it will remove all the checkpoints. 
 - Describe any known limitations with your change.
none
 - Please run any tests or examples that can exercise your modified code.
done.

2020-10-28 08:12 UTC, miguelaeh requested changes
Hi, I have some doubts about the logic I would like to completely understand how this is working.
Please take a look at my comments

2020-10-28 08:12 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        declare -p host_2_ip_array > $CHECKPOINT_FILE_PATH
I am bit confused here, this is for the first initialization of the cluster, so I the CHECK_POINT file and COPY_FILE will not exist right?

2020-10-28 08:12 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
> +    info "Initializing Redis now ..."
I would not change this

2020-10-28 08:12 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
> +        debug "Setting up Redis config file..."
Nor this

2020-10-28 08:12 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
> +    debug "done setting Redis config file..."
I think this does not add too much value

2020-10-28 08:12 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    echo "redis_cluster_override_conf done"
Same here

2020-10-29 07:18 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
> +    debug "done setting Redis config file..."
agreed.

2020-10-29 07:21 UTC, larryzhu2018 commented on 6.0/debian-10/Dockerfile
> +    BITNAMI_DEBUG="true"
agreed

2020-10-29 07:25 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        declare -p host_2_ip_array > $CHECKPOINT_FILE_PATH
CHECK_POINT file does not exist and it is created and removed at the end of the function. this is useful when the machine is rebooted during the middle of this function and the look up of a long list of IP addresses can exceed 5 minutes (300 initialDelaySeconds). 
Do not need to worry about COPY_FILE and it is used to tickle the pod so that it does not need to do the work of look up all the IPs when it is copied over to speed up initial bootstrap

2020-10-29 07:25 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
> +    info "Initializing Redis now ..."
agreed

2020-10-29 07:25 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    echo "redis_cluster_override_conf done"
agreed

2020-10-29 08:00 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        declare -p host_2_ip_array > $CHECKPOINT_FILE_PATH
Because of that, I think those two conditions will never be true. The CHECK_POINT_FILE will never exist so the if will not be executed

2020-10-29 20:17 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        declare -p host_2_ip_array > $CHECKPOINT_FILE_PATH
here is the log produced by these. Note that if the startup is fast, we do not need the check point, but if the start is not, we will need to use the cached IPs
```
----
lazhu@lazhu-mac shardmap % kubectl -n redis-cluster logs -f redis-cluster-8 -c redis-cluster
redis-cluster 00:52:17.27 
redis-cluster 00:52:17.27 Welcome to the Bitnami redis-cluster container
redis-cluster 00:52:17.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 00:52:17.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 00:52:17.28 
redis-cluster 00:52:17.28 INFO  ==> ** Starting Redis setup **
redis-cluster 00:52:17.30 DEBUG ==> Validating settings in REDIS_* env vars..
redis-cluster 00:52:17.31 INFO  ==> Initializing Redis now ...
redis-cluster 00:52:17.31 DEBUG ==> Ensuring expected directories/files exist
redis-cluster 00:52:17.34 INFO  ==> Setting up Redis config file
redis-cluster 00:52:17.37 DEBUG ==> done setting Redis config file ...
redis_cluster_override_conf done
redis-cluster 00:52:17.37 DEBUG ==> redis_cluster_update_ips ...
redis-cluster 00:52:17.37 DEBUG ==> redis_cluster_update_ips creating CLUSTER ...
reading /bitnami/redis/data/nodes_checkpoint.sh
redis-cluster 00:52:17.38 DEBUG ==> cached redis-cluster-0.redis-cluster-headless 10.241.33.245
redis-cluster 00:52:17.38 DEBUG ==> cached redis-cluster-1.redis-cluster-headless 10.241.5.136
redis-cluster 00:52:17.38 DEBUG ==> cached redis-cluster-2.redis-cluster-headless 10.241.27.163
redis-cluster 00:52:17.39 DEBUG ==> cached redis-cluster-3.redis-cluster-headless 10.241.31.123
redis-cluster 00:52:17.39 DEBUG ==> cached redis-cluster-4.redis-cluster-headless 10.241.15.28
redis-cluster 00:52:17.39 DEBUG ==> cached redis-cluster-5.redis-cluster-headless 10.241.16.95
redis-cluster 00:52:17.39 DEBUG ==> cached redis-cluster-6.redis-cluster-headless 10.241.39.253
redis-cluster 00:52:17.40 DEBUG ==> cached redis-cluster-7.redis-cluster-headless 10.241.7.100
redis-cluster 00:52:17.40 DEBUG ==> cached redis-cluster-8.redis-cluster-headless 10.241.17.246
redis-cluster 00:52:17.41 DEBUG ==> cached redis-cluster-9.redis-cluster-headless 10.241.33.63
redis-cluster 00:52:17.41 DEBUG ==> cached redis-cluster-10.redis-cluster-headless 10.241.10.43
redis-cluster 00:52:17.41 DEBUG ==> cached redis-cluster-11.redis-cluster-headless 10.241.16.203
redis-cluster 00:52:17.41 DEBUG ==> cached redis-cluster-12.redis-cluster-headless 10.241.31.210
redis-cluster 00:52:17.42 DEBUG ==> cached redis-cluster-13.redis-cluster-headless 10.241.13.134
redis-cluster 00:52:17.42 DEBUG ==> cached redis-cluster-14.redis-cluster-headless 10.241.23.203
redis-cluster 00:52:17.42 DEBUG ==> cached redis-cluster-15.redis-cluster-headless 10.241.37.9
redis-cluster 00:52:17.43 DEBUG ==> cached redis-cluster-16.redis-cluster-headless 10.241.8.186
redis-cluster 00:52:17.43 DEBUG ==> cached redis-cluster-17.redis-cluster-headless 10.241.6.9
redis-cluster 00:52:17.43 DEBUG ==> cached redis-cluster-18.redis-cluster-headless 10.241.40.51
redis-cluster 00:52:17.44 DEBUG ==> cached redis-cluster-19.redis-cluster-headless 10.241.1.114
redis-cluster 00:52:17.44 DEBUG ==> cached redis-cluster-20.redis-cluster-headless 10.241.24.249
redis-cluster 00:52:17.44 DEBUG ==> cached redis-cluster-21.redis-cluster-headless 10.241.37.246
redis-cluster 00:52:17.45 DEBUG ==> cached redis-cluster-22.redis-cluster-headless 10.241.14.104
redis-cluster 00:52:17.45 DEBUG ==> cached redis-cluster-23.redis-cluster-headless 10.241.26.188
redis-cluster 00:52:17.45 DEBUG ==> cached redis-cluster-24.redis-cluster-headless 10.241.38.171
redis-cluster 00:52:17.45 DEBUG ==> cached redis-cluster-25.redis-cluster-headless 10.241.11.117
redis-cluster 00:52:17.46 DEBUG ==> cached redis-cluster-26.redis-cluster-headless 10.241.29.171
redis-cluster 00:52:17.46 DEBUG ==> cached redis-cluster-27.redis-cluster-headless 10.241.39.82
redis-cluster 00:52:17.46 DEBUG ==> cached redis-cluster-28.redis-cluster-headless 10.241.12.183
redis-cluster 00:52:17.47 DEBUG ==> cached redis-cluster-29.redis-cluster-headless 10.241.25.131
redis-cluster 00:52:17.47 DEBUG ==> cached redis-cluster-30.redis-cluster-headless 10.241.38.53
redis-cluster 00:52:17.47 DEBUG ==> cached redis-cluster-31.redis-cluster-headless 10.241.5.155
redis-cluster 00:52:17.48 DEBUG ==> cached redis-cluster-32.redis-cluster-headless 10.241.21.212
redis-cluster 00:52:17.48 DEBUG ==> cached redis-cluster-33.redis-cluster-headless 10.241.30.231
redis-cluster 00:52:17.48 DEBUG ==> cached redis-cluster-34.redis-cluster-headless 10.241.7.101
redis-cluster 00:52:17.48 DEBUG ==> cached redis-cluster-35.redis-cluster-headless 10.241.20.205
redis-cluster 00:52:17.49 DEBUG ==> cached redis-cluster-36.redis-cluster-headless 10.241.35.58
redis-cluster 00:52:17.49 DEBUG ==> cached redis-cluster-37.redis-cluster-headless 10.241.13.137
redis-cluster 00:52:17.49 DEBUG ==> cached redis-cluster-38.redis-cluster-headless 10.241.15.158
redis-cluster 00:52:17.50 DEBUG ==> cached redis-cluster-39.redis-cluster-headless 10.241.30.23
redis-cluster 00:52:17.50 DEBUG ==> cached redis-cluster-40.redis-cluster-headless 10.241.15.29
redis-cluster 00:52:17.50 DEBUG ==> cached redis-cluster-41.redis-cluster-headless 10.241.29.31
redis-cluster 00:52:17.51 DEBUG ==> cached redis-cluster-42.redis-cluster-headless 10.241.34.195
redis-cluster 00:52:17.51 DEBUG ==> cached redis-cluster-43.redis-cluster-headless 10.241.10.44
redis-cluster 00:52:17.51 DEBUG ==> cached redis-cluster-44.redis-cluster-headless 10.241.16.204
redis-cluster 00:52:17.51 DEBUG ==> cached redis-cluster-45.redis-cluster-headless 10.241.31.125
redis-cluster 00:52:17.52 DEBUG ==> cached redis-cluster-46.redis-cluster-headless 10.241.8.187
redis-cluster 00:52:17.52 DEBUG ==> cached redis-cluster-47.redis-cluster-headless 10.241.27.164
redis-cluster 00:52:17.52 DEBUG ==> cached redis-cluster-48.redis-cluster-headless 10.241.33.246
redis-cluster 00:52:17.53 DEBUG ==> cached redis-cluster-49.redis-cluster-headless 10.241.8.54
redis-cluster 00:52:17.53 DEBUG ==> cached redis-cluster-50.redis-cluster-headless 10.241.23.204
redis-cluster 00:52:17.53 DEBUG ==> cached redis-cluster-51.redis-cluster-headless 10.241.39.134
redis-cluster 00:52:17.53 DEBUG ==> cached redis-cluster-52.redis-cluster-headless 10.241.5.105
redis-cluster 00:52:17.54 DEBUG ==> cached redis-cluster-53.redis-cluster-headless 10.241.16.96
redis-cluster 00:52:17.54 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-54.redis-cluster-headless 120 looking up ...
redis-cluster 00:52:17.56 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-54.redis-cluster-headless 120 10.241.37.11 ...
redis-cluster 00:52:17.56 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-55.redis-cluster-headless 120 looking up ...
redis-cluster 00:52:17.57 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-55.redis-cluster-headless 120 10.241.1.115 ...
redis-cluster 00:52:17.58 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-56.redis-cluster-headless 120 looking up ...
redis-cluster 00:52:17.59 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-56.redis-cluster-headless 120 10.241.17.247 ...
redis-cluster 00:52:17.60 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-57.redis-cluster-headless 120 looking up ...
redis-cluster 00:52:17.61 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-57.redis-cluster-headless 120 10.241.33.64 ...
redis-cluster 00:52:17.61 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-58.redis-cluster-headless 120 looking up ...
redis-cluster 00:52:17.63 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-cluster-58.redis-cluster-headless 120 10.241.5.167 ...
redis-cluster 00:52:17.63 DEBUG ==> redis_cluster_update_ips creating CLUSTER for redis-clust [...]

2020-11-03 08:03 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        declare -p host_2_ip_array > $CHECKPOINT_FILE_PATH
Hi,
thank you for the logs. I am sorry I didn't have the time to test this on our side yet. I will do it as soon as possible.

2020-11-06 10:38 UTC, miguelaeh requested changes
Hi @larryzhu2018 ,
I have been testing this on my side, but I am not able to make your log messages appear.
Could you explain the process you are following to obtain that output? 

I have deployed th chart, then killed some of the pods and checked the logs of the pods before and after kill them, but I can't see the log messages.

Not relevant but just in case I changed  locally the debug mesages by echo to see if that was the problem

2020-11-06 10:38 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +          . $CHECKPOINT_FILE_PATH
I continue thinking that, since you are deleting the file in the line 211 this will never be executed, but maybe I am missing something.

2020-11-09 21:50 UTC, larryzhu2018 commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +          . $CHECKPOINT_FILE_PATH
in order to test this, the machine has to reboot in the middle of function redis_cluster_update_ip!
I understand the changes are a bit of hack and difficult to test, and it is not a big trouble for me to patch it when we upgrade. I am thinking if no other user has reported the same issue, we can table this PR :-)

2020-11-16 11:23 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +          . $CHECKPOINT_FILE_PATH
thanks, I will test it again as soon as possible

2020-11-24 10:08 UTC, miguelaeh commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +          . $CHECKPOINT_FILE_PATH
Hi @larryzhu2018,
I think we could wait to see if other users report the same error before merging this. IMHO the changes are difficult to understand and they fix a weird issue. I think this code will add some difficulty to the code maintenance, since it is not really clear what they do just reading the code.
Do you agree with that?

2020-11-24 15:27 UTC, larryzhu2018 commented
Sounds good. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Miguel Ángel Cabrera Miñagorri <notifications@github.com>
Sent: Tuesday, November 24, 2020 2:08:47 AM
To: bitnami/bitnami-docker-redis-cluster <bitnami-docker-redis-cluster@noreply.github.com>
Cc: larryzhu2018 <larryzhu@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [bitnami/bitnami-docker-redis-cluster] cache ip addresses during startup (#14)


@miguelaeh commented on this pull request.

________________________________

In 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fbitnami-docker-redis-cluster%2Fpull%2F14%23discussion_r529394464&data=04%7C01%7C%7C2d76553a96b64e29282508d89060ef68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637418093285079391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MdACMXDESxh%2BX2f%2Bzdij2SSUlheNhs7pPKsOPUYbRT8%3D&reserved=0>:

> +        CHECKPOINT_FILE_PATH=${REDIS_DATA_DIR}/nodes_checkpoint.sh
+        if [[ -f  "$CHECKPOINT_FILE_PATH" ]]; then
+          echo "reading $CHECKPOINT_FILE_PATH"
+          . $CHECKPOINT_FILE_PATH


Hi @larryzhu2018<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flarryzhu2018&data=04%7C01%7C%7C2d76553a96b64e29282508d89060ef68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637418093285079391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TuWMgrWrKF8YtsJ%2FB%2FSVrIp8To0CzkE64usfnGvt3IY%3D&reserved=0>,
I think we could wait to see if other users report the same error before merging this. IMHO the changes are difficult to understand and they fix a weird issue. I think this code will add some difficulty to the code maintenance, since it is not really clear what they do just reading the code.
Do you agree with that?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fbitnami-docker-redis-cluster%2Fpull%2F14%23discussion_r529394464&data=04%7C01%7C%7C2d76553a96b64e29282508d89060ef68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637418093285089386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l5xRn2KN3p%2Bux87g9MoXamVJozVAanasm2MVRNUs1ws%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTDZPHM7D42XINIK22RJIDSROA27ANCNFSM4S5YFW6Q&data=04%7C01%7C%7C2d76553a96b64e29282508d89060ef68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637418093285089386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MoNmmYFnVf%2F63ZWNEYKtyyiI%2FnUI3M23Dws0CMop2Hs%3D&reserved=0>.

2021-04-21 01:24 UTC, closed without merging