Optional and configurable wait before querying nodes during cluster creation
bitnami/bitnami-docker-redis-cluster pull request #16
Opened 2020-11-27 16:38 UTC by mboutet

**Description of the change**

Introduce `REDIS_CLUSTER_CREATOR_WAIT_TIME_AFTER_NODE_READY` env variable to wait before querying nodes' ip during cluster creation.

**Benefits**

In real environment (AKS in my case), the initial cluster creation would often fail because the nodes' ip were not up to date. This PR adds the `REDIS_CLUSTER_CREATOR_WAIT_TIME_AFTER_NODE_READY` env var to specify a delay in seconds to sleep after the wait logic:
https://github.com/bitnami/bitnami-docker-redis-cluster/blob/07620437aa68627f14d668a1edbc1f0d2931c653/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L124-L135
After this wait, the nodes' ip are queried using `wait_for_dns_lookup`.

The `REDIS_CLUSTER_CREATOR_WAIT_TIME_AFTER_NODE_READY` is set to `0` by default so that the behaviour is the same as the current one.

**Possible drawbacks**

None.

**Applicable issues**

Fixes https://github.com/bitnami/charts/issues/2950

**Additional information**

I originally made the fix in my fork back in July 2020 and used that until now. I have deployed from scratch around 50 times since then and the cluster creation succeeded everytime. I'm using a wait of 30s.

2020-11-30 08:59 UTC, javsalgar requested changes
Thank you so much for the PR. I shared my thoughts, please take a look.

2020-11-30 08:59 UTC, javsalgar commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    ips+=($(wait_for_dns_lookup "$node"))
The wait_for_dns_lookup accepts two extra parameters

- retries: number of retries for trying the lookup (default 5)
- seconds: sleep time between retries (default 1)

I think it would make more sense to create two env vars for the two parameters instead of creating a sleep before. Something

`REDIS_CLUSTER_DNS_LOOKUP_RETRIES`
`REDIS_CLUSTER_DNS_LOOKUP_SLEEP`

What do you think?

2020-11-30 16:21 UTC, mboutet commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    ips+=($(wait_for_dns_lookup "$node"))
The problem is that the dns lookup will work even without sleep but that the IP it returns might be stale (because of TTL and/or delays in the Kubernetes API and dns to be updated). Generally, what I observed when the cluster creation job failed is that some of the redis nodes had restarted few seconds before. Since some nodes were restarted by k8s, their IP changed and the DNS lookup returned the old IP which caused the cluster initialization code to fail.

We can also incorporate the two parameters you are proposing in addition of the one I added so that users can tune according to their environment.

2020-12-01 09:17 UTC, javsalgar commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    ips+=($(wait_for_dns_lookup "$node"))
Ok, then I would add a comment clarifying the approach, so we understand better the corner case we are trying to fix. Sounds good to me the idea of adding these two extra parameters.

2020-12-01 14:17 UTC, mboutet commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    ips+=($(wait_for_dns_lookup "$node"))
Good, I'll add some explanation in the README and add the two extra parameters. Are you ok with the name `REDIS_CLUSTER_CREATOR_WAIT_TIME_AFTER_NODE_READY`? Do you have a better name, a shorter one, maybe?

2020-12-01 14:19 UTC, mboutet commented on 6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    ips+=($(wait_for_dns_lookup "$node"))
Perhaps `REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP`?

2020-12-01 15:13 UTC, mboutet commented
Oups, I think my IDE auto-formatted stuff. Let me fix this.

2020-12-02 09:19 UTC, javsalgar approved these changes
Thanks! LGTM

2020-12-02 20:04 UTC, mboutet commented
Is the merge waiting for some kind of CI and/or further testing on your end?

2020-12-03 09:05 UTC, javsalgar commented
Hi,

Yes, it is being run in our CI/CD, but now it can be merged

2020-12-03 09:05 UTC, merged