allow for alternative ports to be configured
bitnami/bitnami-docker-redis-cluster pull request #19
Opened 2021-01-08 03:43 UTC by calvin-pietersen

**Description of the change**

Allows ports to be configured. Previously setting a port using `REDIS_PORT_NUMBER` would not be discovered by the cluster.

**Benefits**

Allows to set different ports per container. e.g
```
  redis-node-0:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_PORT_NUMBER=6379'
    ports:
      - 6379:6379

  redis-node-1:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_PORT_NUMBER=6378'
    ports:
      - 6378:6378

  redis-node-2:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_PORT_NUMBER=6377'
    ports:
      - 6377:6377

  redis-cluster-init:
    image: calvin/redis-cluster
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    environment:
      - 'REDISCLI_AUTH=abc'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-node-0:6379 redis-node-1:6378 redis-node-2:6377'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_AOF_ENABLED=yes'
```

**Possible drawbacks**

No, Should be backwards compatible with previous configuration.

**Applicable issues**

**Additional information**

Most importantly, this is a sneaky work around to the painful issue I was having connecting from my Mac host through virtual box. Given we need to port forward through virtual box, the client needs to be able to hit all container. The client I am using uses `CLUSTER NODES` to discover the nodes in the cluster. Explicitly setting the REDIS_CLUSTER_ANNOUNCE_IP and port for each node lets me port forward through on each port. 
![Screen Shot 2021-01-08 at 2 43 26 pm](https://user-images.githubusercontent.com/16835507/103971910-e525df80-51bf-11eb-9d5b-ac0fccdebd02.png)

```
  redis-node-0:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'REDIS_PORT_NUMBER=6379'
    ports:
      - 6379:6379
    network_mode: host

  redis-node-1:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'REDIS_PORT_NUMBER=6378'
    ports:
      - 6378:6378
    network_mode: host

  redis-node-2:
    image: calvin/redis-cluster
    environment:
      - 'REDIS_PASSWORD=abc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_AOF_ENABLED=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
      - 'REDIS_PORT_NUMBER=6377'
    ports:
      - 6377:6377
    network_mode: host

  redis-cluster-init:
    image: calvin/redis-cluster
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    environment:
      - 'REDISCLI_AUTH=abc'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6378 127.0.0.1:6377'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_AOF_ENABLED=yes'
    network_mode: host
```

```cluster nodes
$334
1ec5a184ae98a77ab31787fa2058111ee43aa25f **127.0.0.1**:6377@16377 master - 0 1610077134875 3 connected 10923-16383
3c083ba006d510b43d9c6b6e209bfb5925cfc655 **127.0.0.1**:6379@16379 myself,master - 0 1610077133000 1 connected 0-5460
f7677160f30376359b4bf092a40caf28c5c9083d **127.0.0.1**:6378@16378 master - 0 1610077133838 2 connected 5461-10922```

2021-01-08 16:07 UTC, FraPazGal commented
Hello @calvin-pietersen,

Thanks for the PR! I want to test this thoroughly as this is a very error prone asset. There is also the fact that we should avoid any breaking changes that may require new versions for the chart bitnami/redis-cluster. I'll come back with feedback as soon as possible, thanks!

2021-01-11 05:05 UTC, calvin-pietersen commented
@FraPazGal - no problem! I did do some tests for backwards compatibility. But the more testing the better!

2021-01-14 20:55 UTC, FraPazGal requested changes
Hi @calvin-pietersen, the internal testing is looking good. I added a few comments, please take a look at them.

2021-01-14 20:55 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +            wait_command="redis-cli -h ${host_and_port[0]} -p ${host_and_port[1]} --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping"
For readability, it would preferable having `to_host_and_port()` return a value instead of using `host_and_port` as a global variable.

2021-01-14 20:55 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        create_command="redis-cli --cluster create ${ip_and_ports[*]} --cluster-replicas ${REDIS_CLUSTER_REPLICAS} --cluster-yes"
Could we have this as `create_command="redis-cli --cluster create ${ip_and_ports[*]} --cluster-replicas ${REDIS_CLUSTER_REPLICAS} --cluster-yes"` and add the tls-related options when `$REDIS_TLS_ENABLED=true` so that we can reduce this `if`?

2021-01-14 20:55 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +to_host_and_port() {
We should check that $1 has some value, for example: 

`local host_and_port="${1:?At least the host is required}"`

Also, could you please add the function description. You can follow the template used in the others.

2021-01-18 15:16 UTC, FraPazGal commented
Hi @calvin-pietersen,

It looks good! I will test this internally and merge it as soon as possible. In the meantime, could you check the conflict on the README?

2021-01-18 22:26 UTC, calvin-pietersen commented on README.md
> +| `REDIS_PORT_NUMBER`                     | Set the Redis(TM) port. Default=: `6379`
@FraPazGal I changes this in the readme as this is the correct conf. I was tempted to refactor `REDIS_PORT` and `REDIS_TLS_PORT` so that they were consistent `REDIS_MASTER_PORT`. ATM sometime it's _PORT and sometimes it's _PORT_NUMBER. I decided against it though when I saw how many changes I'd need to make haha

2021-01-19 12:48 UTC, FraPazGal commented on README.md
> +| `REDIS_PORT_NUMBER`                     | Set the Redis(TM) port. Default=: `6379`
Yes, that change would affect the chart as well, so we would need a PR there. I'll note it down so we can revisit this change when a new major is released both in the container and the chart.

2021-01-20 15:27 UTC, FraPazGal reviewed
Hi @calvin-pietersen,

I put this through internal review and it is almost done, could you please look at my comments?

2021-01-20 15:27 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    host_and_port=($(echo ${1:?At least the host is required} | tr ":" "\n"))
For readability's sake, could we have this divided in two lines? One for the parameters check and one to transform the string? Also, we should add `local` to the variable.

Also, here I would say that having `"` would be necessary so that `At least the host is required` stays as a single string.

2021-01-20 15:27 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    local ip_and_ports=()
Just to follow the same nomenclature used in other bitnami containers, could we rename this variable to something like `sockets`?

2021-01-20 15:27 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        host_and_port=($(to_host_and_port $node))
One of our linters is throwing a few advices about using `"` to avoid globbing and word splitting. I don't think that this is a must here, though I will say that `"${node}"` would be good, WDYT?

2021-01-20 15:27 UTC, FraPazGal commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        host_and_port=($(to_host_and_port $node))
Same question as above with `$node`

2021-01-29 16:53 UTC, FraPazGal approved these changes
Thanks for the PR! The internal review & testing process is taking a bit longer than expected but everything LGTM! If there is any more linter-related changes we'll add them before merging!

2021-02-03 16:54 UTC, merged

2021-02-08 04:30 UTC, calvin-pietersen commented
@FraPazGal it looks like this PR was reverted somehow?

2021-02-08 10:07 UTC, FraPazGal commented
Hello @calvin-pietersen,

Indeed, it seems there was an error in our internal pipeline and the PR got reverted. We will re-lauch it internally and update here as soon as this is fixed. Thank you for your patience!

2021-02-10 14:50 UTC, FraPazGal commented
A new revision https://github.com/bitnami/bitnami-docker-redis-cluster/commit/a3bc23020d55cf22622015f1868d67397a65ff5e was released yesterday that re-introduced the changes. Sorry for the inconvenience and thanks again for the contribution!