Change init cluster logic
bitnami/bitnami-docker-redis-cluster pull request #24
Opened 2021-04-21 09:43 UTC by miguelaeh

**Description of the change**
This PR changes the cluster initialization logic to avoid the need of an extra container that will die after create the cluster. Now one of the containers that are part of the cluster will initialize it if the proper env vars are provided.

**Benefits**
We can get rid of the hooks in the Helm Chart and we reduce the resources consumption.

**Possible drawbacks**

**Applicable issues**

**Additional information**

2021-04-21 15:56 UTC, javsalgar approved these changes

2021-04-22 08:14 UTC, juan131 requested changes

2021-04-22 08:14 UTC, juan131 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
> +set -m
What does this option comes from? I can't see it listed at https://tldp.org/LDP/abs/html/options.html

2021-04-22 08:14 UTC, juan131 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
>  IFS=' ' read -ra nodes <<< "$REDIS_NODES"
Use this instead:
```suggestion
read -ra nodes <<< "$(tr ',;' ' ' <<< "${REDIS_NODES}")"
```

2021-04-22 08:14 UTC, juan131 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
>  fi
It's unnatural to me to use `if ! (condition) ... else .... fi)`. Change the order to avoid negating the condition:
```suggestion
if is_boolean_yes "$REDIS_CLUSTER_CREATOR"; then
    # Start Redis in background
    if am_i_root; then
        gosu "$REDIS_DAEMON_USER" redis-server "${ARGS[@]}" &
    else
        redis-server "${ARGS[@]}" &
    fi
    # Create the cluster
    redis_cluster_create "${nodes[@]}"
    # Bring redis process to foreground
    fg
else
    if am_i_root; then
        exec gosu "$REDIS_DAEMON_USER" redis-server "${ARGS[@]}"
    else
        exec redis-server "${ARGS[@]}"
    fi
fi
```

2021-04-22 08:18 UTC, miguelaeh commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
> +set -m
This is needed in order to use `fg`

2021-04-22 08:19 UTC, miguelaeh commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
>  IFS=' ' read -ra nodes <<< "$REDIS_NODES"
Why is that better than the current one? IMHO it is more complicated to read, also we are using the current approach more times in the code so it is consistent with what we already have

2021-04-22 09:09 UTC, juan131 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
>  IFS=' ' read -ra nodes <<< "$REDIS_NODES"
It is better because it accepts spaces, comas and semicolons as "separators". And, 
It is not consistent with the rest of bash logic we have in other containers. I'd adapt every reference in the code to follow my suggestion.

2021-04-22 09:21 UTC, juan131 commented on 5.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster/run.sh
> +set -m
All right! Please add a reference to the docs:
```suggestion
# Enable job control
# ref https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
set -m
```

2021-04-22 09:49 UTC, juan131 approved these changes
LGTM

2021-04-22 11:07 UTC, merged